### ISSUE TITLE
Return nothing if field doesn't exist

### ISSUE THREAD

**Issue by pizhn** [mauro3/UnPack.jl#15]
I wonder if it's practical to add one, or extend the existing macro that, if the field doesn't exist in the dict I'm tring to unpack,  then just return a nothing, instead of raise an error like:

```
julia> @unpack ll = a.kwargs
ERROR: type NamedTuple has no field ll
Stacktrace:
 [1] getindex
   @ ./namedtuple.jl:118 [inlined]
 [2] getindex(v::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:ooo,), Tuple{Int64}}}, key::Symbol)
   @ Base.Iterators ./iterators.jl:270
 [3] unpack(x::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:ooo,), Tuple{Int64}}}, #unused#::Val{:ll})
   @ UnPack ~/.julia/packages/UnPack/EkESO/src/UnPack.jl:35
 [4] top-level scope
   @ ~/.julia/packages/UnPack/EkESO/src/UnPack.jl:101
```

Because when writing my code, I found that will be helpful, Thanks!

**Comment by tpapp** [comment]
I don't think this would be a good feature, as it (1) hides errors and (2) introduces a type instability.

**Comment by mauro3** [comment]
Thanks for the feedback, but yep, that is not something UnPack will support.  However, you can do it with Default-Dicts: https://juliacollections.github.io/DataStructures.jl/latest/default_dict/
