### ISSUE TITLE
Unpack for JLD2File

### ISSUE THREAD

**Issue by lukasgrunwald** [mauro3/UnPack.jl#24]
I would be nice to be able to use `@pack!` and `@unpack` to quickly store and load values from JLD2File instances. This can be achieved by adding the methods
```
@inline UnPack.unpack(x::JLDFile{MmapIO}, ::Val{f}) where {f} =  x[string(f)]

@inline function UnPack.pack!(file::JLDFile{MmapIO}, ::Val{f}, val) where {f}
    file[string(f)] = val
end
``` 
These methods can be used as
```
using JLD2
using Unpack

x = rand(10)
path = "temp.jld2"
file = jldopen(path, "w")
@pack! file = x # Creates entry with name x
close(file)

file = jldopen("temp.jld2") # contains fields :x
@unpack x = file # Extracts x from the struct
```

Maybe this could be added (with JLD2 as on optional dependency; not sure how that works though)? Happy to try and make a PR if you are open to doing this.

**Comment by mauro3** [comment]
Maybe this could be added as an example to the README?
